doc string validation

diff --git a/.github/workflows/standard_library_tests_and_examples.yml b/.github/workflows/standard_library_tests_and_examples.yml
--- a/.github/workflows/standard_library_tests_and_examples.yml
+++ b/.github/workflows/standard_library_tests_and_examples.yml
@@ -97,6 +97,14 @@ jobs:
           # Ensure `FileCheck` from the pre-installed LLVM 15 package is visible
           echo $(brew --prefix llvm@15)/bin/ >> $GITHUB_PATH
 
+      - name: Validate documentation strings
+        run: |
+          mojo doc -warn-missing-doc-strings -o /dev/null stdlib/src/
+          if [ $? -ne 0 ]; then
+            echo "::error::Documentation string validation failed. Please fix the issues and try again."
+            exit 1
+          fi
+
       - name: Run standard library tests and examples
         run: |
           ./stdlib/scripts/run-tests.sh
